import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { firstValueFrom } from 'rxjs';
import { AdminService } from '../../admin/admin.service';
import { AuthService } from '../../auth/auth.service';
import { BiomedService, EquipmentCatalogItemDto } from '../../biomed/biomed.service';
import { getApiBase, getPublicBase, joinBase } from '../../core/api-base';
import { ModuleTabsComponent } from '../../shared/module-tabs/module-tabs.component';
import { QuickGuideDto, QuickGuidePayload, QuickGuidesService } from '../../quick-guides/quick-guides.service';

interface ClientOption {
  id: string;
  name: string;
  nit?: string | null;
  city?: string | null;
  email?: string | null;
  address?: string | null;
  logoPath?: string | null;
}

@Component({
  selector: 'app-quick-guides',
  standalone: true,
  imports: [CommonModule, FormsModule, ModuleTabsComponent],
  templateUrl: './quick-guides.component.html',
  styleUrl: './quick-guides.component.scss'
})
export class QuickGuidesComponent {
  private readonly apiBase = getApiBase();
  private readonly publicBase = getPublicBase();

  clients: ClientOption[] = [];
  clientSearchTerm = '';
  selectedClientId = '';
  guides: QuickGuideDto[] = [];
  equipmentCatalog: EquipmentCatalogItemDto[] = [];
  clientsLoading = true;
  loading = false;
  saving = false;
  message = '';
  messageType: 'success' | 'error' | 'info' = 'info';
  viewMode: 'list' | 'form' = 'list';
  searchTerm = '';
  editingGuideId: string | null = null;
  visualFile: File | null = null;
  visualFileName = '';
  metadataEditable = false;
  private autoGeneratedDocumentCode = true;
  private catalogEquipmentSelectionKey = '';
  private catalogBrandSelectionKey = '';

  form = this.emptyForm();

  readonly equipmentTypeOptions = [
    'Equipo electromédico',
    'Equipo mecánico o manual',
    'Instrumental o dispositivo sin energía',
    'Accesorio biomédico',
    'Otro'
  ];

  constructor(
    private readonly quickGuides: QuickGuidesService,
    private readonly admin: AdminService,
    private readonly biomed: BiomedService,
    private readonly http: HttpClient,
    private readonly cdr: ChangeDetectorRef,
    public readonly auth: AuthService
  ) {
    void this.init();
  }

  get filteredClients(): ClientOption[] {
    const term = this.clientSearchTerm.toLowerCase().trim();
    if (!term) return this.clients;
    return this.clients.filter((client) =>
      [
        client.name,
        client.nit,
        client.city,
        client.email
      ]
        .map((value) => String(value || '').toLowerCase())
        .join(' ')
        .includes(term)
    );
  }

  get selectableClients(): ClientOption[] {
    const filtered = this.filteredClients;
    const selected = this.selectedClientInfo;
    if (selected && !filtered.some((client) => client.id === selected.id)) {
      return [selected, ...filtered];
    }
    return filtered;
  }

  get selectedClientInfo(): ClientOption | null {
    return this.clients.find((client) => client.id === this.selectedClientId) ?? null;
  }

  get filteredGuides(): QuickGuideDto[] {
    const term = this.searchTerm.toLowerCase().trim();
    return this.guides.filter((guide) => {
      if (!term) return true;
      return [
        guide.equipment_name,
        guide.brand,
        guide.model,
        guide.document_code
      ]
        .map((value) => String(value || '').toLowerCase())
        .join(' ')
        .includes(term);
    });
  }

  get equipmentCatalogNames(): string[] {
    return this.equipmentCatalog.map((item) => item.name);
  }

  get equipmentCatalogBrands(): string[] {
    return this.findCatalogEquipment(this.form.equipmentName)?.brands.map((brand) => brand.name) ?? [];
  }

  get equipmentCatalogModels(): string[] {
    const equipment = this.findCatalogEquipment(this.form.equipmentName);
    const brand = equipment?.brands.find(
      (item) => this.normalizeCatalogSelection(item.name) === this.normalizeCatalogSelection(this.form.brand)
    );
    return brand?.models.map((model) => model.name) ?? [];
  }

  get canCreate(): boolean {
    return this.auth.hasPermission('quick_guides:create');
  }

  get canEdit(): boolean {
    return this.auth.hasPermission('quick_guides:edit');
  }

  get canDelete(): boolean {
    return this.auth.hasPermission('quick_guides:delete');
  }

  get canSelectClient(): boolean {
    return this.auth.hasRole('superuser');
  }

  get isEditing(): boolean {
    return Boolean(this.editingGuideId);
  }

  async init(): Promise<void> {
    this.clientsLoading = true;
    this.refreshViewSoon();
    try {
      const userClient = this.auth.currentUser()?.clientId ?? '';
      if (userClient) {
        this.selectedClientId = userClient;
        const client = await this.loadOwnClient();
        if (client) this.clients = [client];
        this.clientsLoading = false;
        this.refreshViewSoon();
        await this.onClientChange();
        return;
      }

      if (this.auth.hasPermission('clients:manage') || this.auth.hasRole('superuser')) {
        const rows = await this.admin.listClients();
        this.clients = rows.map((row) => ({
          id: row.id,
          name: row.name,
          nit: row.nit,
          city: row.city,
          email: row.email,
          address: row.address ?? null,
          logoPath: row.logo_path ?? null
        }));
        this.selectedClientId = this.clients[0]?.id ?? '';
        this.clientsLoading = false;
        this.refreshViewSoon();
        if (this.selectedClientId) await this.onClientChange();
      }
    } finally {
      this.clientsLoading = false;
      this.refreshViewSoon();
    }
  }

  async onClientChange(): Promise<void> {
    this.resetForm();
    this.refreshViewSoon();
    await Promise.all([this.loadGuides(), this.loadEquipmentCatalog()]);
  }

  async loadGuides(): Promise<void> {
    if (!this.selectedClientId) return;
    this.loading = true;
    this.message = '';
    try {
      this.guides = await this.quickGuides.list(this.selectedClientId);
    } catch (error) {
      console.error(error);
      this.setMessage('No se pudieron cargar las guías rápidas.', 'error');
    } finally {
      this.loading = false;
      this.refreshViewSoon();
    }
  }

  async loadEquipmentCatalog(): Promise<void> {
    if (!this.selectedClientId) return;
    try {
      this.equipmentCatalog = await this.biomed.listEquipmentCatalog(this.selectedClientId);
    } catch {
      this.equipmentCatalog = [];
    } finally {
      this.refreshViewSoon();
    }
  }

  startCreate(): void {
    this.resetForm();
    this.viewMode = 'form';
  }

  editGuide(guide: QuickGuideDto): void {
    this.editingGuideId = guide.id;
    this.visualFile = null;
    this.visualFileName = guide.visual_path ? 'Imagen visual cargada' : '';
    this.form = {
      documentCode: guide.document_code || '',
      version: guide.version || '1.0',
      equipmentName: guide.equipment_name || '',
      equipmentType: guide.equipment_type || '',
      brand: guide.brand || '',
      model: guide.model || '',
      status: 'aprobada',
      responsibleUse: guide.responsible_use || 'Personal asistencial del área',
      placementNotes: guide.placement_notes || '',
      prerequisites: guide.prerequisites || '',
      startupSteps: guide.startup_steps || '',
      shutdownSteps: guide.shutdown_steps || '',
      basicOperation: guide.basic_operation || '',
      alarms: guide.alarms || '',
      cleaningDisinfection: guide.cleaning_disinfection || '',
      emergencyActions: guide.emergency_actions || '',
      supportContact: guide.support_contact || '',
      visualNotes: guide.visual_notes || ''
    };
    this.catalogEquipmentSelectionKey = this.normalizeCatalogSelection(this.form.equipmentName);
    this.catalogBrandSelectionKey = `${this.catalogEquipmentSelectionKey}|${this.normalizeCatalogSelection(this.form.brand)}`;
    this.autoGeneratedDocumentCode = false;
    this.metadataEditable = false;
    this.viewMode = 'form';
  }

  resetForm(): void {
    this.editingGuideId = null;
    this.form = this.emptyForm();
    this.visualFile = null;
    this.visualFileName = '';
    this.catalogEquipmentSelectionKey = '';
    this.catalogBrandSelectionKey = '';
    this.autoGeneratedDocumentCode = true;
    this.metadataEditable = false;
  }

  cancelForm(): void {
    this.resetForm();
    this.viewMode = 'list';
  }

  onEquipmentCatalogChange(): void {
    const nextKey = this.normalizeCatalogSelection(this.form.equipmentName);
    if (nextKey !== this.catalogEquipmentSelectionKey) {
      this.form.brand = '';
      this.form.model = '';
      this.catalogBrandSelectionKey = '';
    }
    this.catalogEquipmentSelectionKey = nextKey;
    this.ensureDocumentCode();
  }

  onBrandCatalogChange(): void {
    const nextKey = `${this.normalizeCatalogSelection(this.form.equipmentName)}|${this.normalizeCatalogSelection(this.form.brand)}`;
    if (nextKey !== this.catalogBrandSelectionKey) {
      this.form.model = '';
    }
    this.catalogBrandSelectionKey = nextKey;
    this.ensureDocumentCode();
  }

  onModelCatalogChange(): void {
    this.ensureDocumentCode();
  }

  onDocumentCodeInput(): void {
    if (this.metadataEditable) {
      this.autoGeneratedDocumentCode = false;
    }
  }

  enableMetadataEdit(): void {
    this.metadataEditable = true;
    this.autoGeneratedDocumentCode = false;
  }

  onVisualSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0] ?? null;
    if (file && !this.isImage(file)) {
      this.visualFile = null;
      this.visualFileName = '';
      input.value = '';
      this.setMessage('La referencia visual debe ser una imagen PNG, JPG o WEBP.', 'error');
      return;
    }
    this.visualFile = file;
    this.visualFileName = file?.name || '';
  }

  async submitGuide(): Promise<void> {
    if (!this.selectedClientId) return;
    const missing = this.validateForm();
    if (missing.length) {
      this.setMessage(`Completa estos campos: ${missing.join(', ')}.`, 'error');
      return;
    }
    this.saving = true;
    try {
      const payload: QuickGuidePayload = {
        ...this.form,
        equipmentName: this.catalogStorageValue(this.form.equipmentName),
        brand: this.catalogStorageValue(this.form.brand),
        model: this.catalogStorageValue(this.form.model),
        status: 'aprobada',
        visual: this.visualFile
      };
      if (this.editingGuideId) {
        await this.quickGuides.update(this.selectedClientId, this.editingGuideId, payload);
        this.setMessage('Guía rápida actualizada correctamente.', 'success');
      } else {
        await this.quickGuides.create(this.selectedClientId, payload);
        this.setMessage('Guía rápida creada correctamente.', 'success');
      }
      await Promise.all([this.loadGuides(), this.loadEquipmentCatalog()]);
      this.cancelForm();
    } catch (error: any) {
      console.error(error);
      this.setMessage(error?.error?.message || 'No se pudo guardar la guía rápida.', 'error');
    } finally {
      this.saving = false;
    }
  }

  async deleteGuide(guide: QuickGuideDto): Promise<void> {
    if (!this.selectedClientId) return;
    const ok = window.confirm(
      `¿Eliminar la guía rápida de ${guide.equipment_name} · ${guide.brand} / ${guide.model}?`
    );
    if (!ok) return;
    await this.quickGuides.delete(this.selectedClientId, guide.id);
    this.setMessage('Guía rápida eliminada.', 'success');
    await this.loadGuides();
  }

  async openPdf(guide: QuickGuideDto): Promise<void> {
    if (!this.selectedClientId) return;
    const blob = await this.quickGuides.downloadPdf(this.selectedClientId, guide.id);
    const url = URL.createObjectURL(blob);
    window.open(url, '_blank');
    setTimeout(() => URL.revokeObjectURL(url), 5000);
  }

  statusLabel(status: string): string {
    const labels: Record<string, string> = {
      borrador: 'Borrador',
      aprobada: 'Aprobada',
      obsoleta: 'Obsoleta'
    };
    return labels[status] || status;
  }

  clientLogoUrl(client: ClientOption | null): string | null {
    if (!client?.logoPath) return null;
    if (client.logoPath.startsWith('http')) return client.logoPath;
    return joinBase(this.publicBase, client.logoPath);
  }

  private async loadOwnClient(): Promise<ClientOption | null> {
    try {
      const row = await firstValueFrom<any>(this.http.get(`${this.apiBase}/clients/me?t=${Date.now()}`));
      return {
        id: row.id,
        name: row.name,
        nit: row.nit,
        city: row.city,
        email: row.email,
        address: row.address ?? null,
        logoPath: row.logo_path ?? null
      };
    } catch {
      return null;
    }
  }

  private emptyForm(): Omit<QuickGuidePayload, 'visual'> {
    return {
      documentCode: '',
      version: '1.0',
      equipmentName: '',
      equipmentType: 'Equipo electromédico',
      brand: '',
      model: '',
      status: 'aprobada',
      responsibleUse: 'Personal asistencial del área',
      placementNotes: '',
      prerequisites: '',
      startupSteps: '',
      shutdownSteps: '',
      basicOperation: '',
      alarms: '',
      cleaningDisinfection: '',
      emergencyActions: '',
      supportContact: 'Almacén o ingeniero biomédico',
      visualNotes: ''
    };
  }

  private validateForm(): string[] {
    const checks: [keyof Omit<QuickGuidePayload, 'visual'>, string][] = [
      ['equipmentName', 'Equipo'],
      ['brand', 'Marca'],
      ['model', 'Modelo'],
      ['basicOperation', 'Operación básica'],
      ['cleaningDisinfection', 'Limpieza y desinfección'],
      ['emergencyActions', 'Emergencia o falla']
    ];
    return checks.filter(([key]) => !String(this.form[key] || '').trim()).map(([, label]) => label);
  }

  private normalizeCatalogSelection(value: unknown): string {
    return String(value || '')
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .trim()
      .replace(/\s+/g, ' ')
      .toLowerCase();
  }

  private catalogStorageValue(value: unknown): string {
    return String(value || '')
      .trim()
      .replace(/\s+/g, ' ')
      .toLocaleUpperCase('es-CO');
  }

  private findCatalogEquipment(name: string): EquipmentCatalogItemDto | undefined {
    const key = this.normalizeCatalogSelection(name);
    return this.equipmentCatalog.find(
      (item) => this.normalizeCatalogSelection(item.name) === key
    );
  }

  private ensureDocumentCode(): void {
    if (!this.autoGeneratedDocumentCode) return;
    this.form.documentCode = this.buildDocumentCode(this.form.brand, this.form.model);
  }

  private buildDocumentCode(brand: string, model: string): string {
    const slug = [brand, model]
      .map((value) =>
        String(value || '')
          .normalize('NFD')
          .replace(/[\u0300-\u036f]/g, '')
          .replace(/[^a-zA-Z0-9]+/g, '-')
          .replace(/^-+|-+$/g, '')
          .toUpperCase()
      )
      .filter(Boolean)
      .join('-');
    return slug ? `GRU-${slug}` : '';
  }

  private isImage(file: File): boolean {
    const name = file.name.toLowerCase();
    return file.type.startsWith('image/') || name.endsWith('.png') || name.endsWith('.jpg') || name.endsWith('.jpeg') || name.endsWith('.webp');
  }

  private setMessage(message: string, type: 'success' | 'error' | 'info'): void {
    this.message = message;
    this.messageType = type;
    this.refreshViewSoon();
  }

  private refreshViewSoon(): void {
    setTimeout(() => {
      this.cdr.detectChanges();
    }, 0);
  }
}
